#!/bin/bash

#SBATCH --job-name="GMTSAR S1A processing"
#SBATCH --qos=short
#SBATCH --account=morsanat
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=2
##SBATCH --ntasks=1
#SBATCH --workdir=/data/scratch/loibldav/GSP/
#SBATCH --output=/data/scratch/loibldav/GSP/Output/Log/PP-S1A-%j-out
#SBATCH --error=/data/scratch/loibldav/GSP/Output/Log/PP-S1A-%j-err
#SBATCH --mail-type=ALL

start=`date +%s`
echo "Processing started"

# sbatch $GSP_directory/PP-start-S1A 
# 1 - $previous_scene
# 2 - $previous_orbit 
# 3 - $current_scene
# 4 - $current_orbit 
# 5 - $swath
# 6 - $work_PATH 
# 7 - $GSP_directory
# 8 - $gmtsar_config_file
# 9 - $output_PATH

previous_scene=$1
previous_orbit=$2
current_scene=$3
current_orbit=$4
swath=$5
work_PATH=$6
GSP_directory=$7
gmtsar_config_file=$8
output_PATH=$9

echo "Arg 0: $0"
echo "Arg 1: $1"
echo "Arg 2: $2"
echo "Arg 3: $3"
echo "Arg 4: $4"
echo "Arg 5: $5"
echo "Arg 6: $6"
echo "Arg 7: $7"
echo "Arg 8: $8"
echo "Arg 9: $9"
echo "Arg 10: $10"

# mkdir -pv $work_PATH/$start/raw

# cd $work_PATH/raw/

# echo "Starting align-tops with options: $1 $2 $3 $4 dem.grd" 
# align_tops.csh $previous_scene $previous_orbit $current_scene $current_orbit dem.grd


cd $work_PATH/F$swath/raw/
ln -s ../../raw/*F$swath* .
    
cd $work_PATH/F$swath/


echo "Starting p2p_S1A_TOPS with options: S1A${1:15:8}_${1:24:6}_F$5 S1A${3:15:8}_${3:24:6}_F$5 $7/$8" 
p2p_S1A_TOPS.csh S1A${previous_scene:15:8}_${previous_scene:24:6}_F$swath S1A${current_scene:15:8}_${current_scene:24:6}_F$swath $GSP_directory/$gmtsar_config_file 


cd $work_PATH/F$swath/intf/
intf_dir=($( ls )) 
        
output_intf_dir=$output_PATH/Interferograms/S1A${previous_scene:15:8}_${previous_scene:24:6}_F$swath"---"S1A${current_scene:15:8}_${current_scene:24:6}_F$swath

mkdir -pv $output_intf_dir

cp ./$intf_dir/*.grd $output_intf_dir 
cp ./$intf_dir/*.png $output_intf_dir 
cp ./$intf_dir/*.kml $output_intf_dir 
cp ./$intf_dir/*.ps $output_intf_dir 
cp ./$intf_dir/*.cpt $output_intf_dir 
cp ./$intf_dir/*.conf $output_intf_dir 



end=`date +%s`

runtime=$((end-start))

echo "Processing finished in $runtime seconds"

