#!/bin/csh -f
# 
# Z. Cakir
#
if ($#argv < 2) then
 echo ""
 echo "usage"
 echo "$0 *.kml merged.kml"
 echo ""
 exit 1
endif

if (-e "merge.kml") then 
 \rm merge.kml
endif


set n = 1
set out = $argv[$#argv]
#echo $out

if (-e $argv[$#argv]) then
 echo ""
 echo " last file given $argv[$#argv] exisits\!!"
 echo " output will be writen to merged.kml"
 @ nk = $#argv 
 set kml = ($argv)
 set out = merge.kml
else
 echo ""
 @ nk = $#argv - 1
 set out = $argv[$#argv]
 #echo $out
 set kml = `echo $argv | awk '{for (i=1;i<NF;i=i+1) printf"%s ",$i}'` 
endif

foreach f ($kml)
   if ($n == 1) then
   awk '$1=="<?xml",$1=="</Placemark>" {print $0}'  $f > ! $out
  else if ($n == $nk) then
   awk '$1=="<Placemark>",$1=="</kml>" {print $0}'  $f >> $out
  else 
   awk '$1=="<Placemark>",$1=="</Placemark>" {print $0}'  $f >> $out
  endif
@ n = $n + 1
end
