#!/bin/bash

#SBATCH --job-name="GSPC S1A"
#SBATCH --qos=medium
#SBATCH --account=morsanat
#SBATCH --mail-type=ALL

start=`date +%s`
echo "Processing started"

# 1 - $previous_scene
# 2 - $previous_orbit 
# 3 - $current_scene
# 4 - $current_orbit 
# 5 - $swath
# 6 - $work_PATH 
# 7 - $GSP_directory
# 8 - $gmtsar_config_file
# 9 - $output_PATH

previous_scene=$1
previous_orbit=$2
current_scene=$3
current_orbit=$4
swath=$5
work_PATH=$6
topo_PATH=$7
gmtsar_config_file=$8
output_PATH=$9

echo "Arg 0: $0"
echo "Arg 1: $1"
echo "Arg 2: $2"
echo "Arg 3: $3"
echo "Arg 4: $4"
echo "Arg 5: $5"
echo "Arg 6: $6"
echo "Arg 7: $7"
echo "Arg 8: $8"
echo "Arg 9: $9"
echo "Arg 10: $10"

job_ID=${previous_scene:15:8}--${current_scene:15:8}

mkdir -pv $work_PATH/pairs/$job_ID/F$swath/raw 
mkdir -pv $work_PATH/pairs/$job_ID/F$swath/topo 
cd $work_PATH/pairs/$job_ID/F$swath/topo; ln -s $topo_PATH/dem.grd .;

cd $work_PATH/raw/$job_ID-aligned/F$swath

echo
echo "- - - - - - - - - - - - - - - - - - - - "
echo "Starting align_tops.csh with options:"
echo "Scene 1: $previous_scene"
echo "Orbit 1: $previous_orbit"
echo "Scene 2: $current_scene"
echo "Orbit 2: $current_orbit"    	

align_tops.csh $previous_scene $previous_orbit $current_scene $current_orbit dem.grd

cd $work_PATH/pairs/$job_ID/F$swath/raw/
ln -s $work_PATH/raw/$job_ID-aligned/F$swath/*F$swath* .
    
cd $work_PATH/pairs/$job_ID/F$swath/

echo 
echo "- - - - - - - - - - - - - - - - - - - - "
echo "Starting p2p_S1A_TOPS with options:"
echo "S1A${previous_scene:15:8}_${previous_scene:24:6}_F$swath"
echo "S1A${current_scene:15:8}_${current_scene:24:6}_F$swath"
echo "$gmtsar_config_file" 

p2p_S1A_TOPS.csh S1A${previous_scene:15:8}_${previous_scene:24:6}_F$swath S1A${current_scene:15:8}_${current_scene:24:6}_F$swath $gmtsar_config_file 


cd $work_PATH/pairs/$job_ID/F$swath/intf/
intf_dir=($( ls )) 
        
output_intf_dir=$output_PATH/Interferograms/S1A${previous_scene:15:8}_${previous_scene:24:6}_F$swath"---"S1A${current_scene:15:8}_${current_scene:24:6}_F$swath

mkdir -pv $output_intf_dir

cp ./$intf_dir/*.grd $output_intf_dir 
cp ./$intf_dir/*.png $output_intf_dir 
cp ./$intf_dir/*.kml $output_intf_dir 
cp ./$intf_dir/*.ps $output_intf_dir 
cp ./$intf_dir/*.cpt $output_intf_dir 
cp ./$intf_dir/*.conf $output_intf_dir 



end=`date +%s`

runtime=$((end-start))

echo "Processing finished in $runtime seconds"

